# The workflow allows running tests and code linting on the default branch.

image: composer:2.0

pipelines:
  default:
    - step:
        name: Lint
        script:
          - composer install
          - composer lint
        caches:
          - composer
